app/Fresns/Panel/Routes/web.php
<?php

/*
 * Fresns (https://fresns.org)
 * Copyright (C) 2021-Present Jevan Tang
 * Released under the Apache-2.0 License.
 */

use App\Fresns\Panel\Http\Controllers\AccountController;
use App\Fresns\Panel\Http\Controllers\AdminController;
use App\Fresns\Panel\Http\Controllers\AppController;
use App\Fresns\Panel\Http\Controllers\AppKeyController;
use App\Fresns\Panel\Http\Controllers\AppManageController;
use App\Fresns\Panel\Http\Controllers\AppUsageController;
use App\Fresns\Panel\Http\Controllers\ChannelController;
use App\Fresns\Panel\Http\Controllers\ClientController;
use App\Fresns\Panel\Http\Controllers\CodeMessageController;
use App\Fresns\Panel\Http\Controllers\CommonController;
use App\Fresns\Panel\Http\Controllers\ContentController;
use App\Fresns\Panel\Http\Controllers\DashboardController;
use App\Fresns\Panel\Http\Controllers\ExtendContentHandlerController;
use App\Fresns\Panel\Http\Controllers\GeneralController;
use App\Fresns\Panel\Http\Controllers\GroupController;
use App\Fresns\Panel\Http\Controllers\InteractionController;
use App\Fresns\Panel\Http\Controllers\LanguageController;
use App\Fresns\Panel\Http\Controllers\LanguagePackController;
use App\Fresns\Panel\Http\Controllers\LoginController;
use App\Fresns\Panel\Http\Controllers\PolicyController;
use App\Fresns\Panel\Http\Controllers\PublishController;
use App\Fresns\Panel\Http\Controllers\RoleController;
use App\Fresns\Panel\Http\Controllers\SendController;
use App\Fresns\Panel\Http\Controllers\SettingController;
use App\Fresns\Panel\Http\Controllers\StickerController;
use App\Fresns\Panel\Http\Controllers\StickerGroupController;
use App\Fresns\Panel\Http\Controllers\StorageController;
use App\Fresns\Panel\Http\Controllers\UpgradeController;
use App\Fresns\Panel\Http\Controllers\UserController;
use App\Fresns\Panel\Http\Controllers\WalletController;
use App\Helpers\CacheHelper;
use App\Helpers\PrimaryHelper;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Route;

try {
    $itemData = PrimaryHelper::fresnsModelByFsid('config', 'panel_configs');

    $loginPath = $itemData?->item_value['path'] ?? 'admin';
} catch (\Exception $e) {
    $loginPath = 'admin';
}

Route::get($loginPath, [LoginController::class, 'showLoginForm'])->name('login.form');
Route::post($loginPath, [LoginController::class, 'login'])->name('login');

Route::middleware(['panelAuth'])->group(function () {
    Route::post('logout', [LoginController::class, 'logout'])->name('logout');

    // fresns upgrade
    Route::post('auto-upgrade', [UpgradeController::class, 'autoUpgrade'])->name('upgrade.auto');
    Route::post('manual-upgrade', [UpgradeController::class, 'manualUpgrade'])->name('upgrade.manual');
    Route::get('upgrade/info', [UpgradeController::class, 'upgradeInfo'])->name('upgrade.info');

    // update config
    Route::prefix('update')->name('update.')->group(function () {
        Route::put('languages/{itemKey}', [CommonController::class, 'updateLanguages'])->name('languages'); // all
        Route::patch('language/{itemKey}/{langTag}', [CommonController::class, 'updateLanguage'])->name('language'); // monolingual
        Route::patch('item/{itemKey}', [CommonController::class, 'updateItem'])->name('item'); // config item
    });
    // search
    Route::prefix('search')->name('search.')->group(function () {
        Route::get('users', [CommonController::class, 'searchUsers'])->name('users');
        Route::get('groups', [CommonController::class, 'searchGroups'])->name('groups');
    });

    // dashboard-home
    Route::get('dashboard', [DashboardController::class, 'show'])->name('dashboard');
    Route::get('dashboard-data', [DashboardController::class, 'dashboardData'])->name('dashboard.data');
    Route::get('composer/diagnose', [DashboardController::class, 'composerDiagnose'])->name('composer.diagnose');
    Route::get('composer/config', [DashboardController::class, 'composerConfigInfo'])->name('composer.config');
    // dashboard-events
    Route::get('events', [DashboardController::class, 'eventList'])->name('events.index');
    // dashboard-caches
    Route::get('caches', [SettingController::class, 'caches'])->name('caches.index');
    Route::any('cache/all/clear', [SettingController::class, 'cacheAllClear'])->name('cache.all.clear');
    Route::post('cache/select/clear', [SettingController::class, 'cacheSelectClear'])->name('cache.select.clear');
    // dashboard-upgrades
    Route::get('upgrades', [UpgradeController::class, 'show'])->name('upgrades');
    Route::patch('upgrade/check', [UpgradeController::class, 'checkFresnsVersion'])->name('upgrade.check');
    // dashboard-admins
    Route::resource('admins', AdminController::class)->only([
        'index', 'store', 'destroy',
    ]);
    // dashboard-settings
    Route::get('settings', [SettingController::class, 'show'])->name('settings');
    Route::put('settings', [SettingController::class, 'update'])->name('settings.update');

    // systems
    Route::prefix('systems')->group(function () {
        // languages
        Route::get('languages', [LanguageController::class, 'index'])->name('languages.index');
        Route::post('languageMenus', [LanguageController::class, 'store'])->name('languageMenus.store');
        Route::put('languageMenus/update-default', [LanguageController::class, 'updateDefaultLanguage'])->name('languageMenus.default.update');
        Route::put('languageMenus/{langTag}', [LanguageController::class, 'update'])->name('languageMenus.update');
        Route::patch('languageMenus/{langTag}/order', [LanguageController::class, 'updateOrder'])->name('languageMenus.order.update');
        Route::delete('languageMenus/{langTag}', [LanguageController::class, 'destroy'])->name('languageMenus.destroy');
        // storage
        Route::get('storage/image', [StorageController::class, 'imageShow'])->name('storage.image.index');
        Route::put('storage/image', [StorageController::class, 'imageUpdate'])->name('storage.image.update');
        Route::get('storage/video', [StorageController::class, 'videoShow'])->name('storage.video.index');
        Route::put('storage/video', [StorageController::class, 'videoUpdate'])->name('storage.video.update');
        Route::get('storage/audio', [StorageController::class, 'audioShow'])->name('storage.audio.index');
        Route::put('storage/audio', [StorageController::class, 'audioUpdate'])->name('storage.audio.update');
        Route::get('storage/document', [StorageController::class, 'documentShow'])->name('storage.document.index');
        Route::put('storage/document', [StorageController::class, 'documentUpdate'])->name('storage.document.update');
        Route::get('storage/substitution', [StorageController::class, 'substitutionShow'])->name('storage.substitution.index');
        Route::put('storage/substitution', [StorageController::class, 'substitutionUpdate'])->name('storage.substitution.update');
        // general
        Route::get('general', [GeneralController::class, 'show'])->name('general.index');
        Route::put('general', [GeneralController::class, 'update'])->name('general.update');
        // policy
        Route::get('policy', [PolicyController::class, 'show'])->name('policy.index');
        Route::put('policy', [PolicyController::class, 'update'])->name('policy.update');
        // send
        Route::get('send', [SendController::class, 'show'])->name('send.index');
        Route::put('send', [SendController::class, 'update'])->name('send.update');
        Route::put('send/verifyCodeTemplate/{itemKey}/sms', [SendController::class, 'updateSms'])->name('send.sms.update');
        Route::put('send/verifyCodeTemplate/{itemKey}/email', [SendController::class, 'updateEmail'])->name('send.email.update');
        // account
        Route::get('account', [AccountController::class, 'show'])->name('account.index');
        Route::put('account', [AccountController::class, 'update'])->name('account.update');
        // wallet
        Route::get('wallet', [WalletController::class, 'show'])->name('wallet.index');
        Route::put('wallet', [WalletController::class, 'update'])->name('wallet.update');
    });

    // operations
    Route::prefix('operations')->group(function () {
        // user
        Route::get('user', [UserController::class, 'show'])->name('user.index');
        Route::put('user', [UserController::class, 'update'])->name('user.update');
        // content
        Route::get('content', [ContentController::class, 'show'])->name('content.index');
        Route::put('content', [ContentController::class, 'update'])->name('content.update');
        Route::patch('content/hashtag-regexp', [ContentController::class, 'updateHashtagRegexp'])->name('content.update.hashtag-regexp');
        // interaction
        Route::get('interaction', [InteractionController::class, 'show'])->name('interaction.index');
        // publish-post
        Route::get('publish/post', [PublishController::class, 'postShow'])->name('publish.post.index');
        Route::put('publish/post', [PublishController::class, 'postUpdate'])->name('publish.post.update');
        // publish-comment
        Route::get('publish/comment', [PublishController::class, 'commentShow'])->name('publish.comment.index');
        Route::put('publish/comment', [PublishController::class, 'commentUpdate'])->name('publish.comment.update');
        // roles
        Route::resource('roles', RoleController::class)->only([
            'index', 'store', 'update', 'destroy',
        ]);
        Route::patch('roles/{role}/order', [RoleController::class, 'updateSortOrder'])->name('roles.order');
        Route::get('roles/{role}/permissions', [RoleController::class, 'showPermissions'])->name('roles.permissions.index');
        Route::put('roles/{role}/permissions', [RoleController::class, 'updatePermissions'])->name('roles.permissions.update');
        // stickers
        Route::resource('stickers', StickerGroupController::class)->only([

app/Fresns/Panel/Http/Controllers/DashboardController.php
<?php

/*
 * Fresns (https://fresns.org)
 * Copyright (C) 2021-Present Jevan Tang
 * Released under the Apache-2.0 License.
 */

namespace App\Fresns\Panel\Http\Controllers;

use App\Helpers\AppHelper;
use App\Helpers\DateHelper;
use App\Models\Account;
use App\Models\App;
use App\Models\Comment;
use App\Models\Config;
use App\Models\Geotag;
use App\Models\Group;
use App\Models\Hashtag;
use App\Models\Post;
use App\Models\SessionKey;
use App\Models\User;
use App\Utilities\AppUtility;
use App\Utilities\CommandUtility;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    public function show()
    {
        $currentVersion = AppUtility::currentVersion();

        $adminCount = Account::ofAdmin()->count();
        $keyCount = SessionKey::count();

        $apps = App::all();
        $upgradeCount = App::where('is_upgrade', true)->count();

        $systemInfo = AppHelper::getSystemInfo();
        $databaseInfo = AppHelper::getDatabaseInfo();
        $timezones = DateHelper::fresnsDatabaseTimezoneNames();

        return view('FsView::dashboard.index', compact('currentVersion', 'adminCount', 'keyCount', 'apps', 'upgradeCount', 'systemInfo', 'databaseInfo', 'timezones'));
    }

    public function dashboardData(Request $request)
    {
        $data = match ($request->type) {
            'news' => AppUtility::fresnsNews(),
            'checkVersion' => AppUtility::checkVersion(),
            'accountCount' => Account::count(),
            'userCount' => User::count(),
            'groupCount' => Group::count(),
            'hashtagCount' => Hashtag::count(),
            'geotagCount' => Geotag::count(),
            'postCount' => Post::count(),
            'commentCount' => Comment::count(),
        };

        return response()->json($data);
    }

    public function composerDiagnose()
    {
        $diagnose = CommandUtility::getComposerProcess(['diagnose'])->run()->getOutput();

        return $diagnose;
    }

    public function composerConfigInfo()
    {
        $configInfo = CommandUtility::getComposerProcess(['config', '-g', '-l'])->run()->getOutput();

        return $configInfo;
    }

    // events
    public function eventList()
    {
        $upgradeCount = App::where('is_upgrade', true)->count();

        // config keys
        $configKeys = [
            'subscribe_items',
            'crontab_items',
        ];
        $configs = Config::whereIn('item_key', $configKeys)->get();

        foreach ($configs as $config) {
            $params[$config->item_key] = $config->item_value;
        }

        $subscribeList = $params['subscribe_items'];
        $crontabList = $params['crontab_items'];

        return view('FsView::dashboard.events', compact('upgradeCount', 'subscribeList', 'crontabList'));
    }
}

app/Fresns/Panel/Resources/views/dashboard/admins.blade.php
@extends('FsView::commons.sidebarLayout')

@section('sidebar')
    @include('FsView::dashboard.sidebar')
@endsection

@section('content')
    <div class="row mb-4 border-bottom">
        <div class="col-lg-7">
            <h3>{{ __('FsLang::panel.sidebar_admins') }}</h3>
            <p class="text-secondary">{{ __('FsLang::panel.sidebar_admins_intro') }}</p>
        </div>
        <div class="col-lg-5">
            <div class="input-group mt-2 mb-4 justify-content-lg-end">
                @if($isFounder)
                    <button class="btn btn-primary" type="button" data-bs-toggle="modal" data-bs-target="#newAdmin"><i class="bi bi-plus-circle-dotted"></i> {{ __('FsLang::panel.button_add_admin') }}</button>
                @endif
                {{-- <a class="btn btn-outline-secondary" href="#" role="button">{{ __('FsLang::panel.button_support') }}</a> --}}
            </div>
        </div>
    </div>
    <!--Admin List-->
    <div class="table-responsive">
        <table class="table table-hover align-middle text-nowrap">
            <thead>
                <tr class="table-info">
                    <th scope="col">ID</th>
                    <th scope="col">AID</th>
                    <th scope="col">{{ __('FsLang::panel.admin_add_form_account') }}</th>
                    <th scope="col">{{ __('FsLang::panel.table_options') }}</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($admins as $admin)
                    <tr>
                        <td>{{ $admin->id }} </td>
                        <td>{{ $admin->aid }} </td>
                        <td>
                            <span class="badge bg-light text-dark"><i class="bi bi-envelope"></i>
                                @if ($admin->email)
                                    {{ $admin->secret_email }}
                                @else
                                    None
                                @endif
                            </span>
                            <span class="badge bg-light text-dark"><i class="bi bi-phone"></i>
                                @if ($admin->pure_phone)
                                    +{{ $admin->country_code }} {{ $admin->secret_pure_phone }}
                                @else
                                    None
                                @endif
                            </span>
                        </td>
                        <td>
                            @if($isFounder && $admin->id != \Auth::user()->id)
                                <form action="{{ route('panel.admins.destroy', $admin) }}" method="post">
                                    @csrf
                                    @method('delete')
                                    <button type="submit" class="btn btn-link btn-sm text-danger fresns-link delete-button">{{ __('FsLang::panel.button_delete') }}</button>
                                </form>
                            @endif
                            {{-- old delete --}}
                            {{-- @if ($admin->id != \Auth::user()->id)
                                <form action="{{ route('panel.admins.destroy', $admin) }}" method="post">
                                    @csrf
                                    @method('delete')
                                    <button type="submit" class="btn btn-link btn-sm text-danger fresns-link delete-button">{{ __('FsLang::panel.button_delete') }}</button>
                                </form>
                            @endif --}}
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    <!-- Add Modal -->
    <div class="modal fade" id="newAdmin" tabindex="-1" aria-labelledby="newAdmin" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">{{ __('FsLang::panel.admin_add_title') }}</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form action="{{ route('panel.admins.store') }}" class="mb-3" method="post">
                        @csrf
                        <div class="input-group">
                            <span class="input-group-text">{{ __('FsLang::panel.admin_add_form_account') }}</span>
                            <input type="text" name="accountName" class="form-control" placeholder="{{ __('FsLang::panel.admin_add_form_account_placeholder') }}">
                            <button class="btn btn-outline-secondary" type="submit" id="folderInstall-button">{{ __('FsLang::panel.admin_add_form_account_btn') }}</button>
                        </div>
                        <div class="form-text"><i class="bi bi-info-circle"></i> {{ __('FsLang::panel.admin_add_form_account_desc') }}</div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

app/Fresns/Panel/Resources/views/dashboard/caches.blade.php
@extends('FsView::commons.sidebarLayout')

@section('sidebar')
    @include('FsView::dashboard.sidebar')
@endsection

@section('content')
    <!--header-->
    <div class="row mb-4">
        <div class="col-lg-7">
            <h3>{{ __('FsLang::panel.sidebar_caches') }}</h3>
            <p class="text-secondary">{{ __('FsLang::panel.sidebar_caches_intro') }}</p>
        </div>
        <div class="col-lg-5">
            <div class="input-group mt-2 mb-4 justify-content-lg-end">
                <a class="btn btn-outline-danger" href="{{ route('panel.cache.all.clear') }}"><i class="bi bi-trash3"></i> {{ __('FsLang::panel.button_clear_all_cache') }}</a>
                {{-- <a class="btn btn-outline-secondary" href="#" role="button">{{ __('FsLang::panel.button_support') }}</a> --}}
            </div>
        </div>
        <!--tab-list-->
        <ul class="nav nav-tabs" id="myTab" role="tablist">
            <li class="nav-item" role="presentation">
                <button class="nav-link active" id="config-tab" data-bs-toggle="tab" data-bs-target="#config" type="button" role="tab" aria-controls="config" aria-selected="true">{{ __('FsLang::panel.sidebar_caches_tab_config') }}</button>
            </li>
            <li class="nav-item" role="presentation">
                <button class="nav-link" id="data-tab" data-bs-toggle="tab" data-bs-target="#data" type="button" role="tab" aria-controls="data" aria-selected="false">{{ __('FsLang::panel.sidebar_caches_tab_data') }}</button>
            </li>
        </ul>
    </div>

    <!--tab content-->
    <div class="tab-content" id="cacheTabContent">
        <!--config-->
        <div class="tab-pane fade row show active" id="config" role="tabpanel" aria-labelledby="config-tab">
            <form class="col-md-6" action="{{ route('panel.cache.select.clear') }}" method="post">
                @csrf
                <input type="hidden" name="type" value="config" />

                <div class="ms-lg-5">
                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" value="1" id="fresnsSystem" name="fresnsSystem">
                        <label class="form-check-label" for="fresnsSystem">{{ __('FsLang::panel.cache_fresns_system') }}</label>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" value="1" id="fresnsConfig" name="fresnsConfig">
                        <label class="form-check-label" for="fresnsConfig">{{ __('FsLang::panel.cache_fresns_config') }}</label>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" value="1" id="fresnsExtend" name="fresnsExtend">
                        <label class="form-check-label" for="fresnsExtend">{{ __('FsLang::panel.cache_fresns_extend') }}</label>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" value="1" id="fresnsView" name="fresnsView">
                        <label class="form-check-label" for="fresnsView">{{ __('FsLang::panel.cache_fresns_view') }}</label>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" value="1" id="fresnsRoute" name="fresnsRoute">
                        <label class="form-check-label" for="fresnsRoute">{{ __('FsLang::panel.cache_fresns_route') }}</label>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" value="1" id="fresnsEvent" name="fresnsEvent">
                        <label class="form-check-label" for="fresnsEvent">{{ __('FsLang::panel.cache_fresns_event') }}</label>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" value="1" id="fresnsSchedule" name="fresnsSchedule">
                        <label class="form-check-label" for="fresnsSchedule">{{ __('FsLang::panel.cache_fresns_schedule') }}</label>
                    </div>

                    <button type="submit" class="btn btn-success mt-4">{{ __('FsLang::panel.button_clear_cache') }}</button>
                </div>
            </form>
        </div>

        <!--data-->
        <div class="tab-pane fade row" id="data" role="tabpanel" aria-labelledby="data-tab">
            <form class="col-md-6" action="{{ route('panel.cache.select.clear') }}" method="post">
                @csrf
                <input type="hidden" name="type" value="data" />

                <div class="ms-lg-5">
                    <div class="input-group mb-3">
                        <span class="input-group-text">{{ __('FsLang::panel.table_type') }}</span>
                        <select class="form-select" id="cacheType" name="cacheType">
                            <option value="user">{{ __('FsLang::panel.user') }}</option>
                            <option value="group">{{ __('FsLang::panel.group') }}</option>
                            <option value="hashtag">{{ __('FsLang::panel.hashtag') }}</option>
                            <option value="post">{{ __('FsLang::panel.post') }}</option>
                            <option value="comment">{{ __('FsLang::panel.comment') }}</option>
                            <option value="file">{{ __('FsLang::panel.file') }}</option>
                            <option value="extend">{{ __('FsLang::panel.extend') }}</option>
                        </select>
                    </div>
                    <div class="input-group mb-3">
                        <span class="input-group-text">FsID</span>
                        <input type="text" class="form-control" id="cacheFsid" name="cacheFsid" required placeholder="FsID">
                    </div>

                    <button type="submit" class="btn btn-success mt-4">{{ __('FsLang::panel.button_clear_cache') }}</button>
                </div>
            </form>
        </div>

    </div>
@endsection

app/Fresns/Panel/Resources/views/dashboard/events.blade.php
@extends('FsView::commons.sidebarLayout')

@section('sidebar')
    @include('FsView::dashboard.sidebar')
@endsection

@section('content')
    <div class="row mb-4 border-bottom">
        <div class="col-lg-7">
            <h3>{{ __('FsLang::panel.sidebar_events') }}</h3>
            <p class="text-secondary">{{ __('FsLang::panel.sidebar_events_intro') }}</p>
        </div>
        <div class="col-lg-5">
            <div class="input-group mt-2 mb-4 justify-content-lg-end">
                {{-- <a class="btn btn-outline-secondary" href="#" role="button">{{ __('FsLang::panel.button_support') }}</a> --}}
            </div>
        </div>
    </div>
    <!--Event-->
    <div class="row">
        <!--Crontab List-->
        <div class="col-lg-6">
            <div class="table-responsive">
                <table class="table table-hover align-middle text-nowrap">
                    <thead>
                        <tr class="table-info">
                            <th colspan="3" class="text-center">{{ __('FsLang::panel.sidebar_events_tab_crontab') }}</th>
                        </tr>
                        <tr class="table-secondary">
                            <th scope="col">{{ __('FsLang::panel.table_plugin') }}</th>
                            <th scope="col">{{ __('FsLang::panel.table_command_word') }}</th>
                            <th scope="col">{{ __('FsLang::panel.event_crontab_time') }} <i class="bi bi-info-circle" data-bs-toggle="tooltip" data-bs-placement="top" title="{{ __('FsLang::panel.event_crontab_time_desc') }}"></i></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($crontabList as $crontab)
                            <tr>
                                <td>{{ $crontab['fskey'] }} </td>
                                <td>{{ $crontab['cmdWord'] }} </td>
                                <td>{{ $crontab['cronTableFormat'] }} </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
        <!--Subscribe List-->
        <div class="col-lg-6">
            <div class="table-responsive">
                <table class="table table-hover align-middle text-nowrap">
                    <thead>
                        <tr class="table-info">
                            <th colspan="4" class="text-center">{{ __('FsLang::panel.sidebar_events_tab_subscribe') }}</th>
                        </tr>
                        <tr class="table-secondary">
                            <th scope="col">{{ __('FsLang::panel.table_type') }}</th>
                            <th scope="col">{{ __('FsLang::panel.table_plugin') }}</th>
                            <th scope="col">{{ __('FsLang::panel.table_command_word') }}</th>
                            <th scope="col">{{ __('FsLang::panel.event_subscribe_subject') }}</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($subscribeList as $sub)
                            <tr>
                                <td>{{ $sub['type'] }} </td>
                                <td>{{ $sub['fskey'] }} </td>
                                <td>{{ $sub['cmdWord'] }} </td>
                                <td>{{ $sub['subject'] }} </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection

app/Fresns/Panel/Resources/views/dashboard/sidebar.blade.php
<div class="col-lg-2 fresns-sidebar mt-3 mt-lg-0">
    <nav class="navbar navbar-expand-lg navbar-light flex-lg-column shadow" style="background-color:#e3f2fd;">
        <div class="container-fluid d-lg-flex flex-lg-column">
            <span class="navbar-brand">{{ __('FsLang::panel.menu_dashboard') }}</span>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav d-flex flex-column">
                    <li class="nav-item">
                        <a class="nav-link {{ Route::is('panel.dashboard*') ? 'active' : '' }} " href="{{ route('panel.dashboard') }}">{{ __('FsLang::panel.sidebar_home') }}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {{ Route::is('panel.admins*') ? 'active' : '' }}" href="{{ route('panel.admins.index') }}">{{ __('FsLang::panel.sidebar_admins') }}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {{ Route::is('panel.events*') ? 'active' : '' }}" href="{{ route('panel.events.index') }}">{{ __('FsLang::panel.sidebar_events') }}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {{ Route::is('panel.caches*') ? 'active' : '' }}" href="{{ route('panel.caches.index') }}">{{ __('FsLang::panel.sidebar_caches') }}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {{ Route::is('panel.upgrades*') ? 'active' : '' }} " href="{{ route('panel.upgrades') }}">
                            {{ __('FsLang::panel.sidebar_upgrades') }}
                            @if($upgradeCount > 0)
                                <span class="badge rounded-pill bg-danger">{{ $upgradeCount }}</span>
                            @endif
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {{ Route::is('panel.settings*') ? 'active' : '' }}" href="{{ route('panel.settings') }}">{{ __('FsLang::panel.sidebar_settings') }}</a>
                    </li>
                    <li class="nav-item d-block d-lg-none my-3 text-secondary">Powered by Fresns</li>
                </ul>
            </div>
        </div>
        <div class="fresns-copyright d-none d-lg-block">Powered by Fresns</div>
    </nav>
</div>