app/Fresns/Panel/Routes/web.php
    Route::get('settings', [SettingController::class, 'show'])->name('settings');
    Route::put('settings', [SettingController::class, 'update'])->name('settings.update');

    // systems
    Route::prefix('systems')->group(function () {
        // languages
        Route::get('languages', [LanguageController::class, 'index'])->name('languages.index');
        Route::post('languageMenus', [LanguageController::class, 'store'])->name('languageMenus.store');
        Route::put('languageMenus/update-default', [LanguageController::class, 'updateDefaultLanguage'])->name('languageMenus.default.update');
        Route::put('languageMenus/{langTag}', [LanguageController::class, 'update'])->name('languageMenus.update');
        Route::patch('languageMenus/{langTag}/order', [LanguageController::class, 'updateOrder'])->name('languageMenus.order.update');
        Route::delete('languageMenus/{langTag}', [LanguageController::class, 'destroy'])->name('languageMenus.destroy');
        // storage
        Route::get('storage/image', [StorageController::class, 'imageShow'])->name('storage.image.index');
        Route::put('storage/image', [StorageController::class, 'imageUpdate'])->name('storage.image.update');
        Route::get('storage/video', [StorageController::class, 'videoShow'])->name('storage.video.index');
        Route::put('storage/video', [StorageController::class, 'videoUpdate'])->name('storage.video.update');
        Route::get('storage/audio', [StorageController::class, 'audioShow'])->name('storage.audio.index');
        Route::put('storage/audio', [StorageController::class, 'audioUpdate'])->name('storage.audio.update');
        Route::get('storage/document', [StorageController::class, 'documentShow'])->name('storage.document.index');
        Route::put('storage/document', [StorageController::class, 'documentUpdate'])->name('storage.document.update');
        Route::get('storage/substitution', [StorageController::class, 'substitutionShow'])->name('storage.substitution.index');
        Route::put('storage/substitution', [StorageController::class, 'substitutionUpdate'])->name('storage.substitution.update');
        // general
        Route::get('general', [GeneralController::class, 'show'])->name('general.index');
        Route::put('general', [GeneralController::class, 'update'])->name('general.update');
        // policy
        Route::get('policy', [PolicyController::class, 'show'])->name('policy.index');
        Route::put('policy', [PolicyController::class, 'update'])->name('policy.update');
        // send
        Route::get('send', [SendController::class, 'show'])->name('send.index');
        Route::put('send', [SendController::class, 'update'])->name('send.update');
        Route::put('send/verifyCodeTemplate/{itemKey}/sms', [SendController::class, 'updateSms'])->name('send.sms.update');
        Route::put('send/verifyCodeTemplate/{itemKey}/email', [SendController::class, 'updateEmail'])->name('send.email.update');
        // account
        Route::get('account', [AccountController::class, 'show'])->name('account.index');
        Route::put('account', [AccountController::class, 'update'])->name('account.update');
        // wallet
        Route::get('wallet', [WalletController::class, 'show'])->name('wallet.index');
        Route::put('wallet', [WalletController::class, 'update'])->name('wallet.update');
    });

    // operations
    Route::prefix('operations')->group(function () {
        // user
        Route::get('user', [UserController::class, 'show'])->name('user.index');
        Route::put('user', [UserController::class, 'update'])->name('user.update');
        // content
        Route::get('content', [ContentController::class, 'show'])->name('content.index');
        Route::put('content', [ContentController::class, 'update'])->name('content.update');
        Route::patch('content/hashtag-regexp', [ContentController::class, 'updateHashtagRegexp'])->name('content.update.hashtag-regexp');
        // interaction
        Route::get('interaction', [InteractionController::class, 'show'])->name('interaction.index');
        // publish-post
        Route::get('publish/post', [PublishController::class, 'postShow'])->name('publish.post.index');
        Route::put('publish/post', [PublishController::class, 'postUpdate'])->name('publish.post.update');
        // publish-comment
        Route::get('publish/comment', [PublishController::class, 'commentShow'])->name('publish.comment.index');
        Route::put('publish/comment', [PublishController::class, 'commentUpdate'])->name('publish.comment.update');
        // roles
        Route::resource('roles', RoleController::class)->only([
            'index', 'store', 'update', 'destroy',
        ]);
        Route::patch('roles/{role}/order', [RoleController::class, 'updateSortOrder'])->name('roles.order');
        Route::get('roles/{role}/permissions', [RoleController::class, 'showPermissions'])->name('roles.permissions.index');
        Route::put('roles/{role}/permissions', [RoleController::class, 'updatePermissions'])->name('roles.permissions.update');
        // stickers
        Route::resource('stickers', StickerGroupController::class)->only([
            'index', 'store', 'update', 'destroy',
        ]);
        Route::patch('stickers/{sticker}/order', [StickerGroupController::class, 'updateSortOrder'])->name('stickers.order');
        Route::put('sticker-images/batch', [StickerController::class, 'batchUpdate'])->name('sticker-images.batch.update');
        Route::resource('sticker-images', StickerController::class)->only([
            'index', 'store', 'update', 'destroy',
        ])->parameters([
            'sticker-images' => 'stickerImage',
        ]);
        // groups
        Route::resource('groups', GroupController::class)->only([
            'index', 'store', 'update',
        ]);
        Route::patch('groups/{group}/order', [GroupController::class, 'updateSortOrder'])->name('groups.order');
        Route::patch('groups/{group}/recommend-order', [GroupController::class, 'updateRecommendSortOrder'])->name('groups.recommend-order');
        Route::patch('groups/{group}/status', [GroupController::class, 'updateStatus'])->name('groups.status');
        Route::put('groups/{group}/merge', [GroupController::class, 'mergeGroup'])->name('groups.merge');
    });

    // extends
    Route::prefix('extends')->group(function () {
        // content-handler
        Route::get('content-handler', [ExtendContentHandlerController::class, 'index'])->name('content-handler.index');
        Route::put('content-handler', [ExtendContentHandlerController::class, 'update'])->name('content-handler.update');
    });

    // app usages
    Route::prefix('app-usages')->name('app-usages.')->group(function () {
        Route::get('{usageType}', [AppUsageController::class, 'show'])->name('index');
        Route::post('{usageType}/store', [AppUsageController::class, 'store'])->name('store');
        Route::put('update/{id}', [AppUsageController::class, 'update'])->name('update');
        Route::delete('destroy/{id}', [AppUsageController::class, 'destroy'])->name('destroy');
        Route::patch('order/{id}', [AppUsageController::class, 'updateOrder'])->name('update-order');
    });

    // clients
    Route::prefix('clients')->group(function () {
        // channels
        Route::get('channels', [ChannelController::class, 'index'])->name('channels.index');
        Route::put('channels/{type}', [ChannelController::class, 'update'])->name('channels.update');
        // language pack
        Route::resource('language-packs', LanguagePackController::class)->only([
            'index', 'store', 'update', 'destroy',
        ]);
        // code messages
        Route::resource('code-messages', CodeMessageController::class)->only([
            'index', 'store', 'update', 'destroy',
        ]);
        // path
        Route::get('paths', [ClientController::class, 'pathIndex'])->name('paths.index');
        Route::put('paths', [ClientController::class, 'pathUpdate'])->name('paths.update');
        // app key
        Route::resource('keys', AppKeyController::class)->only([
            'index', 'store', 'update', 'destroy',
        ]);
        Route::patch('keys/{key}/reset', [AppKeyController::class, 'reset'])->name('keys.reset');
        // basic
        Route::get('basic', [ClientController::class, 'basicIndex'])->name('client.basic');
        Route::put('basic', [ClientController::class, 'basicUpdate'])->name('client.basic.update');
        // status
        Route::get('status', [ClientController::class, 'statusIndex'])->name('client.status');
        Route::put('status', [ClientController::class, 'statusUpdate'])->name('client.status.update');
        // web engine
        Route::put('web-engine', [ClientController::class, 'engineUpdate'])->name('client.engine.update');
    });

    // app center
    Route::prefix('app-center')->name('app-center.')->group(function () {
        // apps
        Route::get('plugins', [AppController::class, 'plugins'])->name('plugins');
        Route::get('themes', [AppController::class, 'themes'])->name('themes');
        Route::get('apps', [AppController::class, 'apps'])->name('apps');
        // marketplace
        Route::get('marketplace', [AppController::class, 'iframe'])->name('marketplace');
        // settings
        Route::get('settings', [AppController::class, 'iframe'])->name('plugin.settings');
        Route::get('functions', [AppController::class, 'iframe'])->name('theme.functions');
    });

    // plugin manage
    Route::prefix('plugin')->name('plugin.')->group(function () {
        // dashboard upgrade page
        Route::patch('update-code', [AppManageController::class, 'updateCode'])->name('update.code');
        // plugin install and upgrade
        Route::put('install', [AppManageController::class, 'install'])->name('install');
        Route::put('upgrade', [AppManageController::class, 'upgrade'])->name('upgrade');

app/Fresns/Panel/Resources/views/operations/groups.blade.php
@extends('FsView::commons.sidebarLayout')

@section('sidebar')
    @include('FsView::operations.sidebar')
@endsection

@section('content')
    <!--header-->
    <div class="row mb-4">
        <div class="col-lg-7">
            <h3>{{ __('FsLang::panel.sidebar_groups') }}</h3>
            <p class="text-secondary">{{ __('FsLang::panel.sidebar_groups_intro') }}</p>
        </div>
        <div class="col-lg-5">
            <div class="input-group mt-2 mb-4 justify-content-lg-end">
                <button class="btn btn-primary" type="button" data-bs-toggle="modal" data-action="{{ route('panel.groups.store') }}" data-bs-target="#groupModal"><i class="bi bi-plus-circle-dotted"></i> {{ __('FsLang::panel.button_add_group') }}</button>
                {{-- <a class="btn btn-outline-secondary" href="#" role="button">{{ __('FsLang::panel.button_support') }}</a> --}}
            </div>
        </div>
        <ul class="nav nav-tabs">
            <li class="nav-item"><a class="nav-link {{ request('type') ? '' : 'active' }}" href="{{ route('panel.groups.index') }}">{{ __('FsLang::panel.sidebar_groups_tab_active') }}</a></li>
            <li class="nav-item"><a class="nav-link {{ request('type') == 'deactivate' ? 'active' : '' }}" href="{{ route('panel.groups.index', ['type' => 'deactivate']) }}">{{ __('FsLang::panel.sidebar_groups_tab_deactivate') }}</a></li>
            <li class="nav-item"><a class="nav-link {{ request('type') == 'recommend' ? 'active' : '' }}" href="{{ route('panel.groups.index', ['type' => 'recommend']) }}">{{ __('FsLang::panel.sidebar_groups_tab_recommend') }}</a></li>
        </ul>
    </div>

    <!--back-->
    @if (request('parentId'))
        <div class="mb-4">
            <a class="btn btn-outline-primary" href="{{ request()->fullUrlWithQuery(['parentId' => $parentGroup?->parentGroup?->id]) }}" role="button"><i class="bi bi-arrow-left"></i></a>
            <span class="ms-2">{{ $parentGroup->getLangContent('name', $defaultLanguage) }}</span>
        </div>
    @endif

    <!--list-->
    <div class="table-responsive">
        <table class="table table-hover align-middle text-nowrap">
            <thead>
                <tr class="table-info">
                    @if (request('type'))
                        @if (request('type') == 'recommend')
                            <th scope="col" style="width:4rem;">{{ __('FsLang::panel.table_recommend_order') }}</th>
                        @endif
                        <th scope="col">{{ __('FsLang::panel.group_table_parent_group') }}</th>
                    @else
                        <th scope="col" style="width:4rem;">{{ __('FsLang::panel.table_order') }}</th>
                    @endif
                    <th scope="col">{{ __('FsLang::panel.table_name') }}</th>
                    <th scope="col">{{ __('FsLang::panel.group_table_privacy') }}</th>
                    <th scope="col">{{ __('FsLang::panel.group_table_follow') }}</th>
                    <th scope="col">{{ __('FsLang::panel.group_table_admins') }}</th>
                    <th scope="col">{{ __('FsLang::panel.group_table_post_permissions') }}</th>
                    <th scope="col">{{ __('FsLang::panel.group_table_comment_permissions') }}</th>
                    <th scope="col">{{ __('FsLang::panel.group_table_subgroup') }}</th>
                    <th scope="col" style="width:10rem;">{{ __('FsLang::panel.table_options') }}</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($groups as $group)
                    <tr>
                        @if (request('type'))
                            @if (request('type') == 'recommend')
                                <td><input type="number" class="form-control input-number update-order" data-action="{{ route('panel.groups.recommend-order', $group->id) }}" value="{{ $group->recommend_sort_order }}"></td>
                            @endif
                            <td>{{ $group?->parentGroup?->getLangContent('name', $defaultLanguage) }}</td>
                        @else
                            <td><input type="number" class="form-control input-number update-order" data-action="{{ route('panel.groups.order', $group->id) }}" value="{{ $group->sort_order }}"></td>
                        @endif
                        <td>
                            @if ($group->getCoverUrl())
                                <img src="{{ $group->getCoverUrl() }}" width="24" height="24">
                            @endif

                            {{ $group->getLangContent('name', $defaultLanguage) }}

                            @if (request('type') != 'recommend' && $group->is_recommend)
                                <span class="badge rounded-pill text-bg-warning fs-9">{{ __('FsLang::panel.recommend') }}</span>
                            @endif
                        </td>
                        <td>{{ $typeModeLabels[$group->privacy] ?? '' }}</td>
                        <td>
                            @if ($group->follow_type == 1)
                                {{ __('FsLang::panel.group_follow_option_fresns') }}
                            @elseif ($group->follow_type == 2)
                                {{ __('FsLang::panel.group_follow_option_plugin') }} <span class="badge bg-light text-dark">{{ optional($group->plugin)->name }}</span>
                            @else
                                {{ __('FsLang::panel.option_close') }}
                            @endif
                        </td>
                        <td>
                            @foreach ($group->admins as $user)
                                <span class="badge bg-light text-dark">{{ $user->nickname }}</span>
                            @endforeach
                        </td>
                        <td>
                            @if ($group->permissions['can_publish'] ?? false)
                                <span class="badge bg-light text-dark">{{ $permissionLabels[$group->permissions['publish_post'] ?? false] ?? '' }}</span>
                            @else
                                <span class="badge bg-light text-secondary">{{ __('FsLang::panel.option_close') }}</span>
                            @endif
                        </td>
                        <td>
                            @if ($group->permissions['can_publish'] ?? false)
                                <span class="badge bg-light text-dark">{{ $permissionLabels[$group->permissions['publish_comment'] ?? false] ?? '' }}</span>
                            @else
                                <i class="bi bi-dash-lg text-secondary"></i>
                            @endif
                        </td>
                        <td>
                            @if ($group->subgroup_count)
                                <a class="badge bg-light text-primary" href="{{ route('panel.groups.index', ['parentId' => $group->id]) }}">{{ $group->subgroup_count }}</a>
                            @else
                                <span class="badge bg-light text-dark">{{ $group->subgroup_count }}</span>
                            @endif
                        </td>
                        <td>
                            <form action="{{ route('panel.groups.status', ['group' => $group->id]) }}" method="post">
                                @csrf
                                @method('patch')
                                <button type="button" class="btn btn-outline-primary btn-sm"
                                    data-bs-toggle="modal"
                                    data-bs-target="#groupModal"
                                    data-action="{{ route('panel.groups.update', $group->id) }}"
                                    data-parent-group-name="{{ $group?->parentGroup?->getLangContent('name', $defaultLanguage) }}"
                                    data-default-name="{{ $group->getLangContent('name', $defaultLanguage) }}"
                                    data-default-description="{{ $group->getLangContent('description', $defaultLanguage) }}"
                                    data-cover-url="{{ $group->getCoverUrl() }}"
                                    data-banner-url="{{ $group->getBannerUrl() }}"
                                    data-params="{{ $group->toJson() }}"
                                    data-admin-users="{{ $group->admins }}">
                                    {{ __('FsLang::panel.button_edit') }}
                                </button>

                                <button type="button" class="btn btn-outline-success btn-sm"
                                    data-bs-toggle="modal"
                                    data-bs-target="#moveModal"
                                    data-action="{{ route('panel.groups.merge', $group->id) }}"
                                    data-default-name="{{ $group->getLangContent('name', $defaultLanguage) }}"
                                    data-group-id="{{ $group->id }}">
                                    {{ __('FsLang::panel.button_group_move') }}
                                </button>

                                @if ($group->is_enabled)
                                    <button type="submit" class="btn btn-link link-danger ms-1 fresns-link fs-7">{{ __('FsLang::panel.button_deactivate') }}</button>
                                @else
                                    <button type="submit" class="btn btn-outline-warning btn-sm">{{ __('FsLang::panel.button_activate') }}</button>
                                @endif
                            </form>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
    @if ($groups instanceof \Illuminate\Pagination\LengthAwarePaginator)
        {{ $groups->appends(request()->all())->links() }}
    @endif

    <!--group edit modal-->
    @include('FsView::operations.group-edit-modal')
@endsection

app/Fresns/Panel/Resources/views/operations/sidebar.blade.php
<div class="col-lg-2 fresns-sidebar mt-3 mt-lg-0">
    <nav class="navbar navbar-expand-lg navbar-light flex-lg-column shadow" style="background-color:#e3f2fd;">
        <div class="container-fluid d-lg-flex flex-lg-column">
            <span class="navbar-brand">{{ __('FsLang::panel.menu_operations') }}</span>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav d-flex flex-column">
                    <li class="nav-item"><a class="nav-link {{ Route::is('panel.user.*') ? 'active' : ''}}" href="{{ route('panel.user.index') }}">{{ __('FsLang::panel.sidebar_user') }}</a></li>
                    <li class="nav-item"><a class="nav-link {{ Route::is('panel.content.*') ? 'active' : ''}}" href="{{ route('panel.content.index') }}">{{ __('FsLang::panel.sidebar_content') }}</a></li>
                    <li class="nav-item"><a class="nav-link {{ Route::is('panel.interaction.*') ? 'active' : '' }}" href="{{ route('panel.interaction.index') }}">{{ __('FsLang::panel.sidebar_interaction') }}</a></li>
                    <li class="nav-item"><a class="nav-link {{ Route::is('panel.publish.*') ? 'active' : '' }}" href="{{ route('panel.publish.post.index') }}">{{ __('FsLang::panel.sidebar_publish') }}</a></li>
                    <li><hr style="margin: 0.5rem 0"></li>
                    <li class="nav-item"><a class="nav-link {{ Route::is('panel.roles.*') ? 'active' : '' }}" href="{{ route('panel.roles.index') }}">{{ __('FsLang::panel.sidebar_roles') }}</a></li>
                    <li class="nav-item"><a class="nav-link {{ Route::is('panel.stickers.*') ? 'active' : '' }}" href="{{ route('panel.stickers.index') }}">{{ __('FsLang::panel.sidebar_stickers') }}</a></li>
                    <li class="nav-item"><a class="nav-link {{ Route::is('panel.groups.*') ? 'active' : '' }}" href="{{ route('panel.groups.index') }}">{{ __('FsLang::panel.sidebar_groups') }}</a></li>
                    <li class="nav-item d-block d-lg-none my-3 text-secondary">Powered by Fresns</li>
                </ul>
            </div>
        </div>
        <div class="fresns-copyright d-none d-lg-block">Powered by Fresns</div>
    </nav>
</div>